### ISSUE TITLE
make send protected (send is private)

### ISSUE THREAD

**Issue by markkimsal** [amphp/beanstalk#2]
I'm trying to subclass the client to add my own method (statsJob to get stats) but I cannot call $this->send from a subclass because it's private and not protected.

**Comment by kelunik** [comment]
How about just PRing that method? :-)

**Comment by kelunik** [comment]
@markkimsal ping.

**Comment by zhikiri** [comment]
@kelunik I think this issue can be closed by https://github.com/amphp/beanstalk/pull/5

**Comment by kelunik** [comment]
Yes, was about to comment that as well.
