### ISSUE TITLE
Unexpected connection close

### ISSUE THREAD

**Issue by ekhvalov** [amphp/beanstalk#29]
Hello. First of all thank you for your work.
We faced a problem that happens when beanstalk close connection after daemon reboot for example. When connection is closed reserve promise does not received any answer and stuck.

**Comment by kelunik** [comment]
I guess this is the problem fixed in https://github.com/amphp/beanstalk/pull/30?

**Comment by ekhvalov** [comment]
Yes it is.

**Comment by ekhvalov** [comment]
Can you create branch "0.2.x", please? I want to add this update to "0.2.x" version too.

**Comment by kelunik** [comment]
I've created https://github.com/amphp/beanstalk/tree/0.2.x from https://github.com/amphp/beanstalk/tree/v0.2.5.

**Comment by ekhvalov** [comment]
Nice! Please review [#32 ](https://github.com/amphp/beanstalk/pull/32)
