### ISSUE TITLE
CONTACT FORM ERROR..DON'T KNOW WHY THIS IS COMING

### ISSUE THREAD

**Issue by NishutSuman** [amphp/beanstalk#33]
Please, Sir, resolve my problem by providing proper solutions. My contact us page is not working while it used with amp plugin. But after deactivating the amp plugin the form is working properly.
So please find the issue coming in the screenshot below.
![Screenshot (22)](https://user-images.githubusercontent.com/67069496/86266860-769a1080-bbe3-11ea-8a97-2b1e91516ccd.png)

**Comment by kelunik** [comment]
Hey @NishutSuman, it seems you have opened an issue on the wrong package. This is a library for talking the the beanstalk queue service and not some plugin for anything.
