### ISSUE TITLE
Add further commands

### ISSUE THREAD

**Issue by kelunik** [amphp/beanstalk#4]
~~Mostly stats commands are missing I think.~~ `listTubes()` is missing.

**Comment by zhikiri** [comment]
hi @kelunik. I can help you with this

**Comment by kelunik** [comment]
Great!

**Comment by zhikiri** [comment]
@kelunik here you can find the PR https://github.com/amphp/beanstalk/pull/5

**Comment by zhikiri** [comment]
@kelunik seems can be closed

**Comment by kelunik** [comment]
Yes, I think there are no more commands left, thanks again!

**Comment by kelunik** [comment]
@zhikiri I've adjusted your PR, because it needs to return the correct types: cbf8cfa9ca5e3100f0d3d578e77653b9da564656

I'm also reopening this issue, because `listTubes()` is still missing.

**Comment by zhikiri** [comment]
@kelunik but what about auto conversion for types ? When client will check `$stats->job_running > 6` it will be converted from `string` to `int` automatically

**Comment by zhikiri** [comment]
and yes, list tubes is missing, your right

**Comment by kelunik** [comment]
@zhikiri Yes, that mostly works, but it doesn't work with `strict_types=1` or `assertSame` / `===`.

**Comment by zhikiri** [comment]
@kelunik so true

**Comment by kelunik** [comment]
Closing now due to #6 being merged. Thanks!
